### ISSUE TITLE
http://inhouseprotocols.com/index.html

### ISSUE THREAD

**Issue by Anonim-tech** [arunhpatil/GoogleScholar#2]
May I ask the source code of this website to learn.
http://inhouseprotocols.com/index.html

thanks

**Comment by arunhpatil** [comment]
Hi @Anonim-tech, I have attached html, css and php pages in the zip file. Let me know if you need any further details. 

[inhouseprotocol_home.zip](https://github.com/arunhpatil/GoogleScholar/files/4008569/inhouseprotocol_home.zip)
